version: "3.1"
services:
  mongo_db:
    container_name: "mongo_db"
    image: mongo:4.4.3
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - volume_database:/data/db
volumes:
  volume_database: