version: 2.1

jobs:
  build-test-project:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.2 
          docker_layer_caching: true 
      - run:
          name: Build
          command: mvn clean install -Dmaven.test.skip=true
      - run:
            name: run all test
            command: mvn test -Dtest=!TodoRepositoryTest         
      - run:
          name: Build Image
          command: docker build .

workflows:
  maven-build:
    jobs:
      - build-test-project