version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: yusufislamdemir/todoproject
    docker:
      - image: circleci/buildpack-deps:stretch

jobs:
  build-test-project:
    executor: docker-publisher  
    steps:
      - checkout
      - run:
          name: maven Build
          command: mvn clean install -P prod -Dmaven.test.skip=true 
      - run:
            name: run all test
            command: mvn test -P prod
      - run:
            name: docker-build-save
            command: | 
             docker build -t $IMAGE_NAME:latest .
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
               

  test-project:
    machine:
      image: ubuntu-2004:202010-01 
      docker_layer_caching: true
    steps:
      - checkout
      - run:
            name: run all test
            command: mvn test -P dev        

workflows:
  maven-build-test:
    jobs:
    - build-test-project:
        filters:
         branches:
           only:
            - master          
  
  checkout-test:
    jobs:
    - test-project:
        filters:
         branches:
           ignore:
            - master          

        