version: 2.1

jobs:
  build-test-project:
    machine:
      image: ubuntu-2004:202010-01 
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Build
          command: mvn clean install -Dmaven.test.skip=true
      - run:
            name: run all test
            command: mvn test        
      - run:
          name: Build Image
          command: docker build -t todo .
      - run:
          name: save image
          command: |
           mkdir docker-image
           docker save -o docker-image/image.tar todo    

workflows:
  maven-build:
    jobs:
      - build-test-project