version: 2.1
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0  
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.2 
          docker_layer_caching: true 
      - run:
          name: Build
          command: mvn clean install -Dmaven.test.skip=true
      - run:
          name: Build Image
          command: docker build .   
      - run:
          name: Test
          command: mvn test 
          

workflows:
  sample:
    jobs:
      - build-and-test
