version: 2.1

orbs:
 maven: circleci/maven@1.3.0
executors:
  docker-executor:
     docker:
      - image: cimg/openjdk:11.0

  machine-executor:
    machine:
     image: ubuntu-2204:2022.04.2
    environment:
     architecture: "amd64"
     platform: "linux/amd64"
jobs:
  build-project:
    executor: docker-executor 
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.2 
          docker_layer_caching: true 
      - run:
          name: Build
          command: mvn clean install -Dmaven.test.skip=true
      - run:
          name: Build Image
          command: docker build .   

workflows:
  maven-build:
    jobs:
      - build-project
  maven-test:
    jobs: 
    - maven/test:
        executor: machine-executor    
  