version: 2.1

executors:
  docker-executor:
     docker:
      - image: cimg/openjdk:11.0

  machine-executor:
    machine:
     image: ubuntu-2204:2022.04.2
    environment:
     architecture: "amd64"
     platform: "linux/amd64"
jobs:
  build-test-project:
    executor: docker-executor 
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.2 
          docker_layer_caching: true 
      - run:
          name: Build
          command: mvn clean install -Dmaven.test.skip=true
      - run:
          name: Build Image
          command: docker build .
  maven-test:
      executor: machine-executor
      steps:
         - checkout
         - run:
            name: run all test
            command: mvn test    
workflows:
  maven-build:
    jobs:
      - build-test-project 
    