version: 2.1
jobs:
  build-test-project:
    machine:
      image: ubuntu-2004:202010-01 
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: maven Build
          command: mvn clean install -P prod -Dmaven.test.skip=true 
      - run:
            name: run all test
            command: mvn test -P prod
      - run:
            name: docker-build
            command: | 
             docker build -t yusufislamdemir/todoproject:latest .
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
               

  test-project:
    machine:
      image: ubuntu-2004:202010-01 
      docker_layer_caching: true
    steps:
      - checkout
      - run:
            name: run all test
            command: mvn test -P dev        

workflows:
  maven-build-test:
    jobs:
    - build-test-project:
        filters:
         branches:
           only:
            - master          
  
  checkout-test:
    jobs:
    - test-project:
        filters:
         branches:
           ignore:
            - master          

        