version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: todoproject
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  build-test-project:
    machine:
      image: ubuntu-2004:202010-01 
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: maven Build
          command: mvn clean install -P prod -Dmaven.test.skip=true 
      - run:
            name: run all test
            command: mvn test -P prod
      - run:
            name: docker-build
            command: | 
             docker build -t todoproject .
      - run:
           name: save image an archive
           command: |
             mkdir docker-image
             docker save -o docker-image/image.tar todoproject
      - persist_to_workspace:
          root: .
          paths:
          - docker-image

  push-dockerhub-project:
    machine:
      image: ubuntu-2004:202010-01 
      docker_layer_caching: true
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Load archived Docker image
          command: docker load -i ./docker-image/image.tar todoproject
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$docker_password" | docker login -u "$docker_username" --password-stdin
            docker push todoproject             

  test-project:
    machine:
      image: ubuntu-2004:202010-01 
      docker_layer_caching: true
    steps:
      - checkout
      - run:
            name: run all test
            command: mvn test -P dev        

workflows:
  maven-build-test:
    jobs:
    - build-test-project:
        filters:
         branches:
           only:
            - master          
    - push-dockerhub-project:
        requires:
          - build-test-project
        filters:
         branches:
           only:
            - master

  checkout-test:
    jobs:
    - test-project:
        filters:
         branches:
           ignore:
            - master          

        