version: 2.1

jobs:
  build-test-project:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.2 
          docker_layer_caching: true 
      - run:
          name: Build
          command: mvn clean install -Dmaven.test.skip=true
      - run:
            name: run all test
            command: mvn test         
      - run:
          name: Build Image
          command: docker build .

workflows:
  maven-build:
    jobs:
      - build-test-project